name: Windows build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: |
          pyinstaller app.spec

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Build NSIS installer
        run: |
          $Version = (Get-Content -Path "${{ github.workspace }}\version.txt").Trim()
          Write-Host "Building installer for version $Version"
          $ProjectDir = "${{ github.workspace }}"
          & makensis /XPROJECT_DIR="$ProjectDir" /XVERSION="$Version" "$ProjectDir\installer\nsis\installer.nsi"
        shell: pwsh

      - name: Upload artifact
        run: |
          $Version = (Get-Content -Path "${{ github.workspace }}\version.txt").Trim()
          Write-Host "Version: $Version"
          Write-Host "Installer: AndroidTVRemote-$Version-Installer.exe"
          # Rename for clarity in artifacts list
          Copy-Item -Path "AndroidTVRemote-$Version-Installer.exe" -Destination "AndroidTVRemote-Installer.exe" -Force
        shell: pwsh
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/AndroidTVRemote/**
            AndroidTVRemote-*-Installer.exe
            AndroidTVRemote-Installer.exe