name: Windows build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          python -m PyInstaller app.spec

      - name: Install NSIS
        run: |
          choco install nsis -y

      - name: Build NSIS installer
        run: |
          $Version = (Get-Content -Path "${{ github.workspace }}\version.txt").Trim()
          Write-Host "Building installer for version $Version"
          $ProjectDir = "${{ github.workspace }}"
          & makensis /XPROJECT_DIR="$ProjectDir" /XVERSION="$Version" "$ProjectDir\installer\nsis\installer.nsi"
        shell: pwsh

      - name: Prepare artifacts
        run: |
          $Version = (Get-Content -Path "${{ github.workspace }}\version.txt").Trim()
          Write-Host "Version: $Version"
          Write-Host "Installer: AndroidTVRemote-$Version-Installer.exe"
          
          # Check if installer exists and rename for clarity in artifacts list
          if (Test-Path "AndroidTVRemote-$Version-Installer.exe") {
            Copy-Item -Path "AndroidTVRemote-$Version-Installer.exe" -Destination "AndroidTVRemote-Installer.exe" -Force
            Write-Host "Installer found and renamed for clarity in artifacts"
          } else {
            Write-Host "Warning: Installer not found at expected path"
          }
        shell: pwsh
        
      - name: Upload app build
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: dist/AndroidTVRemote/**
          
      - name: Upload installer (if exists)
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        continue-on-error: true
        with:
          name: installer
          path: |
            AndroidTVRemote-*-Installer.exe
            AndroidTVRemote-Installer.exe