name: Windows build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller with app.spec
        run: |
          python -m PyInstaller app.spec --clean --noconfirm
        shell: cmd

      - name: Verify build
        run: |
          if (Test-Path "dist\android-tv-remote.exe") {
              Write-Host "Build successful: android-tv-remote.exe created"
              Get-Item "dist\android-tv-remote.exe" | Format-List Name, Length, LastWriteTime
          } else {
              Write-Host "Build failed: executable not found"
              Get-ChildItem "dist" -ErrorAction SilentlyContinue | Format-Table
              exit 1
          }
        shell: pwsh

      - name: Create portable package
        run: |
          $Version = (Get-Content -Path "version.txt").Trim()
          Write-Host "Creating portable package for version $Version"
          
          $PackageDir = "AndroidTVRemote-$Version-Windows"
          New-Item -ItemType Directory -Path $PackageDir -Force
          
          Copy-Item -Path "dist\android-tv-remote.exe" -Destination "$PackageDir\AndroidTVRemote.exe"
          Copy-Item -Path "README.md" -Destination "$PackageDir\" -ErrorAction SilentlyContinue
          Copy-Item -Path "BLUETOOTH.md" -Destination "$PackageDir\" -ErrorAction SilentlyContinue
          Copy-Item -Path "LICENSE" -Destination "$PackageDir\" -ErrorAction SilentlyContinue
          
          "AndroidTVRemote.exe" | Out-File -FilePath "$PackageDir\run.bat" -Encoding ascii
          "Android TV Remote Control (Bluetooth) - Windows Package" | Out-File -FilePath "$PackageDir\README.txt" -Encoding utf8
          
          Compress-Archive -Path $PackageDir -DestinationPath "$PackageDir.zip" -Force
          Write-Host "Package created: $PackageDir.zip"
        shell: pwsh
        
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/android-tv-remote.exe
          
      - name: Upload portable package
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable-package
          path: AndroidTVRemote-*-Windows.zip